CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(200) NOT NULL,
                       description TEXT,
                       category VARCHAR(30) NOT NULL,
                       status VARCHAR(30) NOT NULL,
                       work_date DATE NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);