CREATE TABLE music_tracks (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              title VARCHAR(255) NOT NULL,
                              artist VARCHAR(255),
                              original_filename VARCHAR(255) NOT NULL,
                              stored_filename VARCHAR(255) NOT NULL UNIQUE,
                              content_type VARCHAR(100),
                              file_size_bytes BIGINT NOT NULL,
                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);